on:
  push:
    branches:
      - main
    paths:
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.webp"
      - "community-gathered data/raid-list.json"
      - "community-gathered data/**.csv"
  workflow_dispatch:

jobs:
  create_raid_list_json:
    name: Create the raid list json
    runs-on: ubuntu-latest
    env:
      COMMITTER_NAME_TEXT: '{"false":"${{ github.actor }}", "true":"github-actions[bot]"}'
      COMMITTER_ID_TEXT: '{"false":"${{ github.actor_id }}", "true":"41898282"}'
      TEXT: '{"false":"[${{ github.event.pusher.name }}] Update raid-list.json", "true":"[${{ github.triggering_actor }}] Update raid-list.json"}'
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          path: main
      - name: Check which files were updated
        uses: dorny/paths-filter@v3
        id: changes
        with:
           filters: |
              tables:
                - "**.csv"
           working-directory: "./main"
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      - name: Run the Python script
        if: steps.changes.outputs.tables == 'true'
        run: python main/.github/scripts/create_raid_list.py
      - name: Commit changes
        if: steps.changes.outputs.tables == 'true'
        run: |
          cd ./main/
          git pull --rebase
          git config user.name "${{ env.COMMITTER_NAME }}"
          git config user.email "${{ env.COMMITTER_ID }}+${{ env.COMMITTER_NAME }}@users.noreply.github.com"
          git add ./"community-gathered data"/raid-list.json
          git commit --allow-empty -m "${{ env.COMMIT_MESSAGE }}"
          git push origin
        env:
          COMMITTER_NAME: ${{ fromJSON(env.COMMITTER_NAME_TEXT)[ github.ref_name == 'main' ] }}
          COMMITTER_ID: ${{ fromJSON(env.COMMITTER_ID_TEXT)[ github.ref_name == 'main' ] }}
          COMMIT_MESSAGE: ${{ fromJSON(env.TEXT)[ github.event.pusher.name == '' ] }}
  export_files_on_push:
    name: Export new and modified files, on push
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout io repository content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}
          repository: Matrix4348/matrix4348.github.io
          path: io
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          path: main
      - name: Check which files were updated
        uses: dorny/paths-filter@v3
        id: changes
        with:
           filters: |
              images:
                - "**.png"
                - "**.jpg"
                - "**.jpeg"
                - "**.webp"
              raid_list:
                - './"community-gathered data"/raid-list.json'
              tables:
                - "**.csv"
           working-directory: "./main"
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests
      - name: Update the raid list if needed
        if: steps.changes.outputs.tables == 'true'
        run: python main/.github/scripts/create_raid_list.py
      - name: Put the raid list into the io repository
        if: steps.changes.outputs.raid_list == 'true' || steps.changes.outputs.tables == 'true'
        run: python main/.github/scripts/copy_raid_list_from_main_repository_to_io_repository.py
      - name: Put the images into the io repository
        if: steps.changes.outputs.images == 'true'
        run: python main/.github/scripts/add_new_images_in_main_repository_to_io_repository.py
      - name: Commit changes
        run: |
          cd ./io/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if [ ${{ steps.changes.outputs.raid_list }} == 'true' -o ${{ steps.changes.outputs.tables }} == 'true' ] && [ ${{ steps.changes.outputs.images }} == 'true' ]; then
            git commit --allow-empty -m "Update raid-list.json and loot tables"
          elif [ ${{ steps.changes.outputs.raid_list }} == 'true' -o ${{ steps.changes.outputs.tables }} == 'true' ]; then
            git commit --allow-empty -m "Update raid-list.json"
          elif [ ${{ steps.changes.outputs.images }} == 'true' ]; then
            git commit --allow-empty -m "Update loot tables"
          else
            git commit --allow-empty -m "Empty commit"
          fi
          git push
  export_files_on_workflow_dispatch:
    name: Export new and modified files, on workflow_dispatch
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout io repository content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}
          repository: Matrix4348/matrix4348.github.io
          path: io
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          path: main
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests
      - name: Recreate the raid list if needed
        run: python main/.github/scripts/create_raid_list.py
      - name: Put the raid list into the io repository
        run: python main/.github/scripts/copy_raid_list_from_main_repository_to_io_repository.py
      - name: Put the images into the io repository
        run: python main/.github/scripts/add_new_images_in_main_repository_to_io_repository.py
      - name: Commit changes
        run: |
          cd ./io/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --allow-empty -m "[Manual trigger] Update raid-list.json and loot tables"
          git push
