on:
  push:
    branches:
      - main
    paths:
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.webp"
  workflow_dispatch:

jobs:
  export_images:
    name: Export new and modified 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout io repository content
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}
          repository: Matrix4348/matrix4348.github.io
          path: io
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          path: main
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      - name: Finally run the Python file
        run: python main/.github/scripts/add_new_images_in_main_repository_to_io_repository.py
      - name: Commit changes
        run: |
          cd ./io/
          git config --global user.email "127596209+Matrix4348@users.noreply.github.com"
          git config --global user.name "Workflow"
          git remote set-url origin https://x-access-token:GITHUB_TOKEN@github.com/Matrix4348/matrix4348.github.io.git
          git add .
          git commit --allow-empty -m "Teleport images to another world"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
