on:
  workflow_dispatch:

jobs:
  create_raid_list_json:
    name: Create the raid list json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      #- name: Finally run the Python file
       # run: python .github/scripts/create_raid_list.py
      #- name: Commit changes
       # run: |
        #  git config --global user.email "127596209+Matrix4348@users.noreply.github.com"
      #    git config --global user.name "Workflow"
       #   git add ./"community-gathered data"/raid_list.json
     #     git commit --allow-empty -m "Magically create raid_list.json"
      #    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  add_raid_list_json_to_github_io:
    needs: create_raid_list_json
    permissions:
      contents: write
      pages: write 
    name: Add the raid list json to github.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          #token: ${{ secrets.GITHUB_TOKEN }}
          path: main
      - name: Checkout io repository content
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Matrix4348/matrix4348.github.io
          path: io
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      - name: Finally run the Python file
        run: python main/.github/scripts/create_raid_list.py
      - name: Commit changes
        run: |
          git config --global user.email "127596209+Matrix4348@users.noreply.github.com"
          git config --global user.name "Workflow"
          #git remote add origin https://github.com/Matrix4348/Dragons-of-the-Void---Raid-Loot-Tiers
          git remote add iorigin https://github.com/Matrix4348/matrix4348.github.io

          git remote add all https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git remote set-url --add --push all https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git remote set-url --add --push all https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Matrix4348/matrix4348.github.io

          git add ./io/raid_list.json
          git commit --allow-empty -m "Teleport raid_list.json to another world"
          #git remote set-url --push iorigin https://Matrix4348:$MY_PAT@github.com/Matrix4348/matrix4348.github.io
          #git remote set-url iorigin https://x-access-token:${{ secrets.MY_PAT }}@github.com/${{ github.repository }}
          git push all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MY_PAT: ${{ secrets.MY_PAT }}
