on:
  push:
    branches:
      - main
    paths:
      - "user script/development.user.js"
  workflow_dispatch:
  
jobs:
  inject_raid_list_json:
    name: Inject raid_list.json into the user script before releasing the new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          token: ${{ secrets.MY_PAT }}
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests      
      - name: Run the Python script
        run: python .github/scripts/build_user_script.py
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./"user script"/latest.user.js
          git commit -m "${{ github.event.commits[0].message || '-' }}"
          git push