on:
  push:
    branches:
      - main
    paths:
      - "user script/development.user.js"
  workflow_dispatch:
  
jobs:
  inject_raid_list_json:
    name: Inject raid-list.json into the user script before releasing the new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
        with:
          token: ${{ secrets.MY_PAT }}
          path: main
      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Install the python version needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests
      - name: (Re)build raid-list.json # Especially in case it had to be renamed but was not created yet
        run: python main/.github/scripts/create_raid_list.py     
      - name: Build the user script
        run: python main/.github/scripts/build_user_script.py
      - name: Commit changes
        run: |
          cd ./main/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./"user script"/latest.user.js
          git commit -m "${{ github.event.commits[0].message || '-' }}"
          git pull --rebase --autostash
          git push